version: '3'
services:
  app:
    container_name: full_app
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - ./:/usr/src/app/
    networks:
      - fullstack
  

volumes:
  api:


# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    external: true

